import { createContext, useContext, useMemo, useState, type ReactNode } from 'react'
import { demoPatients, demoSegments } from '../data/demoData'
import type { Patient } from '../types/patient'
import type { TranscriptSegment } from '../types/consultation'

type SOAPDraft = { Subjective: string; Objective: string; Assessment: string; Plan: string }
type ConsultationRecord = { id: string; patient: Patient; transcript: TranscriptSegment[]; note: SOAPDraft; approved: boolean; mode: 'demo' | 'live'; status: 'draft' | 'processing' | 'review' | 'approved' | 'error' }

type ConsultationContextValue = { consultations: ConsultationRecord[]; getConsultation: (id: string) => ConsultationRecord | undefined; createDemoConsultation: (patient?: Patient) => string; updateTranscript: (id: string, transcript: TranscriptSegment[]) => void; updateNote: (id: string, note: Partial<SOAPDraft>) => void; approve: (id: string) => void; setStatus: (id: string, status: ConsultationRecord['status']) => void }
const ConsultationContext = createContext<ConsultationContextValue | null>(null)
const defaultNote: SOAPDraft = { Subjective: 'Persistent dry cough for around 2 weeks. Denies fever, chills, or night sweats. Mild dyspnea on exertion.', Objective: 'Lungs clear bilaterally. Current vitals not documented.', Assessment: 'Persistent cough, unspecified. Suggestions require clinician verification.', Plan: 'Hydration and throat lozenges. Verify medication dose before signing.' }
const makeDemo = (patient = demoPatients[0]): ConsultationRecord => ({ id: `DEMO-${Date.now()}`, patient, transcript: demoSegments, note: defaultNote, approved: false, mode: 'demo', status: 'review' })
export function ConsultationProvider({ children }: { children: ReactNode }) { const [consultations, setConsultations] = useState<ConsultationRecord[]>([makeDemo()]); const getConsultation = (id: string) => consultations.find(c => c.id === id) ?? consultations[0]; const updateTranscript = (id: string, transcript: TranscriptSegment[]) => setConsultations(current => current.map(c => c.id === id ? { ...c, transcript } : c)); const createDemoConsultation = (patient = demoPatients[0]) => { const next = makeDemo(patient); setConsultations(current => [...current, next]); return next.id }; const updateNote = (id: string, note: Partial<SOAPDraft>) => setConsultations(current => current.map(c => c.id === id ? { ...c, note: { ...c.note, ...note } } : c)); const approve = (id: string) => setConsultations(current => current.map(c => c.id === id ? { ...c, approved: true, status: 'approved' } : c)); const setStatus = (id: string, status: ConsultationRecord['status']) => setConsultations(current => current.map(c => c.id === id ? { ...c, status } : c)); const value = useMemo(() => ({ consultations, getConsultation, createDemoConsultation, updateTranscript, updateNote, approve, setStatus }), [consultations]); return <ConsultationContext.Provider value={value}>{children}</ConsultationContext.Provider> }
export function useConsultationStore() { const value = useContext(ConsultationContext); if (!value) throw new Error('useConsultationStore must be used inside ConsultationProvider'); return value }
export type { ConsultationRecord, SOAPDraft }
